project:
  type: website
  output-dir: "docs"

website:
  title: "Sara Grever"
  navbar:
    right:
      - posts-page.qmd
      - icon: github
        href: https://github.com/sgrever
      - icon: linkedin
        href: https://www.linkedin.com/in/saragrever/
format:
  html:
    theme: cosmo
    css: styles.css



